name: gekattendance
description: "A school attendance system using AI-based facial recognition"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.0+1   # For SQLite database
  path_provider: ^2.0.14 # To find paths for database files
  image_picker: ^1.0.7 # Ensure you have the latest version

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  provider: ^6.0.0
  flutter_svg: ^1.0.3
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  fluttertoast: ^8.2.12
  table_calendar: ^3.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets
  assets:
      - assets/images/
      - assets/fonts/
      - assets/icons/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700